// GENERATED by scripts/mkjsheader.sh — do not edit.
// Source of truth: scripts/*.js (edit those, then run the script).
#import <Foundation/Foundation.h>

NS_ASSUME_NONNULL_BEGIN

// From scripts/hintoverlay.js
extern NSString *const kVimbScriptHintoverlay;
// From scripts/vimbcore.js
extern NSString *const kVimbScriptVimbcore;

NS_ASSUME_NONNULL_END
