#!/bin/sh
# Generates VimbScripts.h/.m: one NSString constant per scripts/*.js file.
# Parity with src/scripts/js2h.sh (same job, Objective-C instead of C).
# Run automatically by the Makefile when scripts/*.js change; output is
# committed so a clean checkout builds without regenerating.
#
# Usage: scripts/mkjsheader.sh            (writes VimbScripts.h/.m in macos/)
set -e

DIR="$(cd "$(dirname "$0")" && pwd)"
OUTDIR="$DIR/.."
H="$OUTDIR/VimbScripts.h"
M="$OUTDIR/VimbScripts.m"

# Constant name for a file: hintoverlay.js -> kVimbScriptHintoverlay
const_name() {
    echo "kVimbScript$(basename "$1" .js | perl -ne 'print ucfirst($_)')"
}

{
    echo "// GENERATED by scripts/mkjsheader.sh — do not edit."
    echo "// Source of truth: scripts/*.js (edit those, then run the script)."
    echo "#import <Foundation/Foundation.h>"
    echo ""
    echo "NS_ASSUME_NONNULL_BEGIN"
    echo ""
    for f in "$DIR"/*.js; do
        echo "// From scripts/$(basename "$f")"
        echo "extern NSString *const $(const_name "$f");"
    done
    echo ""
    echo "NS_ASSUME_NONNULL_END"
} > "$H"

{
    echo "// GENERATED by scripts/mkjsheader.sh — do not edit."
    echo "#import \"VimbScripts.h\""
    echo ""
    for f in "$DIR"/*.js; do
        echo "// ---- scripts/$(basename "$f") ----"
        printf 'NSString *const %s = @' "$(const_name "$f")"
        # One single-line literal: escape \ and " and map newlines to \n.
        perl -pe 's/\\/\\\\/g; s/"/\\"/g; s/\r//g; chomp; $_ .= "\\n"' "$f" \
            | tr -d '\n' \
            | sed -e 's/^/"/' -e 's/$/"/'
        echo ";"
        echo ""
    done
} > "$M"

echo "regenerated $(basename "$H"), $(basename "$M") from scripts/*.js"
